name: Build Windows Executable

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      # 1. Checks out your repository's code under $GITHUB_WORKSPACE
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Sets up Python 3.9. You can change the version if needed.
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # 3. Installs Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib

      # 4. Run PyInstaller
      - name: Build executable with PyInstaller
        run: |
          pyinstaller --name "SermonUploader" ^
                      --onefile ^
                      --windowed ^
                      --add-data "client_secret.json;." ^
                      --add-binary "ffmpeg.exe;." ^
                      app.py
                      
      # 5. Upload the artifact
      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: SermonUploader-Windows-x64
          path: dist/SermonUploader.exe