name: Build and Release

on:
  push:
    branches:
      - "master"
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: ${{ runner.os }} on ${{ runner.arch }}
        run: echo "${{ runner.os }} on ${{ runner.arch }}"
      - if: runner.os != 'macOS' || runner.arch != 'ARM64'
        uses: FedericoCarboni/setup-ffmpeg@v3
      - if: runner.os == 'macOS' && runner.arch == 'ARM64'
        run: brew install ffmpeg

      # --- Common Steps ---
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Create client_secret.json
        shell: bash
        run: |
          echo "${{ secrets.CLIENT_SECRET_JSON }}" > client_secret.json

      # --- UNIFIED BUILD COMMAND ---
      # We no longer need to bundle ffmpeg.exe on Windows because setup-ffmpeg adds it to the PATH.
      # This means the build command is now identical for all platforms.
      - name: Build executable with PyInstaller
        # Use a platform-agnostic shell and command
        shell: bash 
        run: |
          # The path separator for --add-data is ":" for bash on all platforms
          pyinstaller --name "SermonUploader" \
                      --onefile \
                      --windowed \
                      --add-data "client_secret.json:." \
                      app.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SermonUploader-${{ matrix.os }}
          path: |
            dist/SermonUploader.exe
            dist/SermonUploader
          if-no-files-found: ignore

  # ===============================================================
  #  JOB 2: Create a GitHub Release and upload build assets
  # ===============================================================
  create_release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create a release

    steps:
      # Step 1: Download all the artifacts (executables) from the 'build' job
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          # Download into a single directory named 'release-assets'
          path: release-assets

      # Step 2: Create the release and upload all files from the 'release-assets' directory
      - name: Create Release and Upload Assets
        uses: ncipollo/release-action@v1
        with:
          # This is the path to the files to upload. The wildcard '**/*' uploads all files in all subdirectories.
          artifacts: "release-assets/**/*"
          # This token is provided by GitHub Actions automatically.
          token: ${{ secrets.GITHUB_TOKEN }}
          # Automatically generate release notes from commits since the last release.
          generateReleaseNotes: true